//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mira_pools")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub pair_id: Uuid,
    pub swaps: i64,
    pub reserve_base: Decimal,
    pub reserve_quote: Decimal,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::token_pairs::Entity",
        from = "Column::PairId",
        to = "super::token_pairs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TokenPairs,
}

impl Related<super::token_pairs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TokenPairs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
