//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sync_status")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tx_first_block_number: i32,
    pub tx_first_block_time: Option<DateTimeWithTimeZone>,
    pub tx_last_block_number: i32,
    pub tx_last_block_time: Option<DateTimeWithTimeZone>,
    pub swaps_first_block_number: i32,
    pub swaps_first_block_time: Option<DateTimeWithTimeZone>,
    pub swaps_last_block_number: i32,
    pub swaps_last_block_time: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
