//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token_pairs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub base_token_details_id: Uuid,
    pub quote_token_details_id: Uuid,
    pub base_address: String,
    pub quote_address: String,
    pub pair_address: String,
    pub base_symbol: String,
    pub quote_symbol: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mira_pools::Entity")]
    MiraPools,
    #[sea_orm(has_many = "super::pair_swaps::Entity")]
    PairSwaps,
    #[sea_orm(
        belongs_to = "super::token::Entity",
        from = "Column::BaseTokenDetailsId",
        to = "super::token::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Token2,
    #[sea_orm(
        belongs_to = "super::token::Entity",
        from = "Column::QuoteTokenDetailsId",
        to = "super::token::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Token1,
}

impl Related<super::mira_pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MiraPools.def()
    }
}

impl Related<super::pair_swaps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PairSwaps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
