//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "token")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub address: String,
    #[sea_orm(unique)]
    pub symbol: String,
    pub name: String,
    pub price: Decimal,
    pub volume24: Decimal,
    pub price_change24: Decimal,
    pub decimals: i32,
    pub high_risk: bool,
    pub no_liquidity: bool,
    pub quoting: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub volume24_usd: Decimal,
    pub liquidity: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::price_data::Entity")]
    PriceData,
    #[sea_orm(has_many = "super::volume_data::Entity")]
    VolumeData,
}

impl Related<super::price_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceData.def()
    }
}

impl Related<super::volume_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VolumeData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
