[default]
server_port_http=8080
data_refresh_interval=300 # seconds
#rpc_url="https://autumn-magical-glade.fuel-mainnet.quiknode.pro/v1/graphql"
#https://rpc.ankr.com/premium-http/fuel/2051d179b3f725afcd27cc235efcd67a84f709abfa6aaedd44de641782be8a2a
#https://mainnet.fuel.network
#rpc_url_one="https://restless-evocative-paper.fuel-mainnet.quiknode.pro/168fb298bd9efd326ed37c8a899adb5f49a9a45e"
rpc_url_two="https://restless-evocative-paper.fuel-mainnet.quiknode.pro"
rpc_url_one="https://mainnet.fuel.network"
rpc_url_three="https://autumn-magical-glade.fuel-mainnet.quiknode.pro/v1/graphql"
db_url="localhost:5432/fuel_data"
db_username="admin"
db_password="admin"
db_min_connections=4
db_max_connections=8
db_sql_logging=false
tx_log_start_block_number=17071554
calculation_window=1480 #minutes
#0x81d5964bfbb24fd994591cc7d0a4137458d746ac0eb7ececb9a9cf2ae966d942
#0x4ea6ccef1215d9479f1024dff70fc055ca538215d2c8c348beddffd54583d0e8
cdi_fuel_token_gateway = "0x4ea6ccef1215d9479f1024dff70fc055ca538215d2c8c348beddffd54583d0e8"
cdi_fuel_token_gateway_dependency = "0x0ceafc5ef55c66912e855917782a3804dc489fb9e27edfd3621ea47d2a281156"
cdi_mira_token_gateway = "0x81d5964bfbb24fd994591cc7d0a4137458d746ac0eb7ececb9a9cf2ae966d942"
cdi_mira_amm = "0x2e40f2b244b98ed6b8204b3de0156c6961f98525c8162f80162fcf53eebd90e7"
mira_swap_event="7938487056892321597"
mira_create_pool="12224862438738316526"
mira_total_supply="17462098202904023478"
mira_pool_max_age=5 #minutes
sentio_url="https://endpoint.sentio.xyz/1delta/fuel-subgraph/swaps_filtered"
sentio_api_key="mHWELZ01Oo3BRfGb0WrhFvryge78baQVT"
